# Generated by Django 2.2.12 on 2022-11-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
