# Generated by Django 4.1.3 on 2022-12-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='contact_number',
            field=models.IntegerField(max_length=13),
        ),
        migrations.AlterField(
            model_name='queries',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
